name = "CartesianRuns"
uuid = "8ac86999-83ee-4abe-ba29-189971ff34fb"
version = "1.0.0-DEV"
authors = ["Vincent Le Chenadec <vincentlechenadec@gmail.com> and contributors"]

[deps]
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"

[compat]
OffsetArrays = "1.17.0"
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
