name = "CartesianRuns"
uuid = "8ac86999-83ee-4abe-ba29-189971ff34fb"
version = "0.1.0"
authors = ["Vincent Le Chenadec <vincentlechenadec@gmail.com> and contributors"]

[deps]

[compat]
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
